### ISSUE TITLE
Calculation Fix

### ISSUE THREAD

**Issue by CptHampton** [Amexy/BandoriEventPtCalculator#1]
I'm pretty sure the event point calculation is wrong (at least for normal events, but I'm sure there's a similar format/structure for the others).
Normal event points should be:
`epGain = Math.floor((50 + Math.floor(yourScore / 10000) + Math.floor(teamScore / 100000)) * bpPercentModifier) * flamesEPModifier;
`
Where:
`teamScore = multiScore - yourScore`

I saw the calculation in [this reddit post](https://www.reddit.com/r/BanGDream/comments/8ccwk7/a_simple_guide_to_events_normal_events/) and took 10 samples, all of which matched up exactly 

The extra `Math.floor` that encompasses everything up to `flamesEPModifier` is because event points are always in multiples of 5 when using flames, so this must be what Bandori is doing

**Comment by Amexy** [comment]
I see. I'll check it out when I get home and use some scores from the
current event and match them up. I already knew it was a bit wonky.

I was referencing the formula from the tumblr page.

*Normal Event Score Formula:*

Points = { Base ( 50 ) + floor[ ( Your Score * 9 ) / 100,000 ] + floor(
Total Score / 100,000 ) } * ( Bonus Points Boost ) * ( Live Boost
Multiplier )

Where ( Your Score ) caps at 1.5m and ( Total Score ) caps at 7.5m.

**Comment by jmillerll** [comment]
Good catch. I just tested your formula and it gave me the correct EP. I'll edit it when I get off work.

**Comment by CptHampton** [comment]
I ran that formula through the data I collected and the scoring section of the formula was off by a point on some of the samples compared to what the game itself listed as my "score points", so I'm pretty sure if you test the formula I posted above it should reflect the points you actually earn in-game or at least hit that target with greater precision.

**Comment by Amexy** [comment]
Good catch. I just tested it, and your formula gave the correct EP.

**Comment by CptHampton** [comment]
So assuming that's right it should carry over to the other event types, too, just switching out how many base points there are, how much `yourScore` is divided by, and using `teamScore` instead of `multiScore`
